name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["NestJS CI"]
    branches: [main]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platforms: ['linux/amd64']

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push DevContainer Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/bitmind-ai/bittensor-devcontainer:latest
            ghcr.io/bitmind-ai/bittensor-devcontainer:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/bitmind-ai/bittensor-devcontainer
            org.opencontainers.image.description=BitMind image for Bittensor development
          platforms: ${{ matrix.platforms }}

      - name: Build and push btcli-api Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./btcli-api/Dockerfile
          push: true
          tags: |
            ghcr.io/bitmind-ai/bittensor-devcontainer:latest
            ghcr.io/bitmind-ai/bittensor-devcontainer:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/bitmind-ai/btcli-api
            org.opencontainers.image.description=BitMind image for btcli JS API
          platforms: ${{ matrix.platforms }}

      # - name: Verify Image
      #   run: docker run --rm ghcr.io/bitmind-ai/bittensor-devcontainer:latest /path/to/your/test/script

